name: CI

on:
  push:
    branches: [devel]
  pull_request:
    branches: [devel]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
        name: Checkout code
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
        name: Install dependencies
      - run: npm run lint
        name: Lint code
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
        name: Checkout code
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
        name: Install dependencies
      - run: npm run format:check
        name: Check code formatting
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
        name: Checkout code
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
        name: Install dependencies
      - run: npm test
        name: Run unit tests
